### PR TITLE
Usermanagement

### PR DESCRIPTION
**Pull request by sclark39**
Adding partial permission support to discordia and adding some user management stuff (create roles, assign roles to members)

also adds support for Member:setMute, Member:setDeaf, Role:setPermissions, Member:set { options }, and Role:set {options}

### CODE REVIEW

**Comment by SinisterRectus** [comment]
- `shallowCopyArray` is redundant. see `table.copy` in `extensions.lua`.
- I don't do any type checking anywhere, so there's no need to implement it now. If you do want it, though, I have a `Error` and `Warning` classes that do not terminate the program. There is currently no difference between the two except for the text coloring and implied severity.
- Formatting
  - Inconsistencies with library: `( param )` vs `(param)` and `i,v` vs `i, v`.
  - Don't use snake_case if you can avoid it (ex: `target_type`)
  - Use UpperCase for class names
  - Use lowercase for file names
  - Use camelCase for everything else

**Comment by sclark39** [comment]
Cool, I'll fix all that.

**Comment by sclark39** [comment]
Let me know if there is anything else that needs adjusting. I am happy to do so.

**Comment by XNBlank** [comment]
Damn, beat me to it. :P

**Pull request merged**
