### PR TITLE
support replies

### PR DESCRIPTION
**Pull request by IsLilyYaGirl**
support message replies

### CODE REVIEW

**Comment by IsLilyYaGirl** [comment]
had this in my personal fork and thought of making a pull request for it

**Comment by IsLilyYaGirl** [comment]
yes i did test it

**Comment by SinisterRectus** [comment]
Hi, thank you for this. The problem with your implementation is that all calls to `message:reply` will include an actual reply with a mention by default. This isn't exactly a breaking change, but it does change the expected behavior of the library, so we should not do this.

I've gone and written my own implementation and opened #294 for people to comment.

**Comment by IsLilyYaGirl** [comment]
i see, thanks

**Pull request closed without merging**
