### PR TITLE
Added an early exit and modified returning message for example in README.md

### PR DESCRIPTION
**Pull request by antonio6643**
To prevent it from continuously calling itself when the command is used.

### CODE REVIEW

**Comment by Tigerism** [comment]
The reply, ``!pong``, is not the same as the command, ``!ping``

**Comment by antonio6643** [comment]
Oh, I thought it was just a regular response. My mistake, I edited the file to put it back as it was.

**Comment by SinisterRectus** [comment]
The readme example is meant to be as simple as possible while still being functional, so I purposefully excluded the author check. This is found, and explained, in the examples folder instead.

I would rather see the change from "!pong" to "pong!", though.

**Comment by antonio6643** [comment]
That makes sense. I'll edit the request again to add it back.

**Comment by SinisterRectus** [comment]
You missed the point of my comment. I don't want the early exit in this example.

**Comment by antonio6643** [comment]
My mistak. My power is out so I'm doing this all from mobile.

**Comment by SinisterRectus** [comment]
Remove the new lines.

**Pull request merged**
