### PR TITLE
Fixed typo in "greater"

### PR DESCRIPTION
**Pull request by Parvulster**

### CODE REVIEW

**Comment by SinisterRectus** [comment]
Can you proofread all of the other docs now? Thanks for volunteering.

**Comment by Parvulster** [comment]
kek

**Comment by SinisterRectus** [comment]
Have you found anything else?

**Comment by SinisterRectus** [comment]
Sorry. I completely forgot to pull this, I did remove the docs from the code, though, so there's no where to pull it to anymore. I may consider opening up the Wiki again so people can submit contributions there.

**Pull request closed without merging**
