### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by senor-init**

### CODE REVIEW

**Comment by SinisterRectus** [comment]
When someone submits a typo fix, I ask that they check the rest of the code and documentation for typos, so if you could, please and thank you.

**Comment by senor-init** [comment]
ok

**Comment by NotSoClassy** [comment]
I found some mistakes:
- [Here](https://github.com/SinisterRectus/Discordia/blob/master/libs/utils/Clock.lua#L5) it should be `an arbitrary interval`
- [Here](https://github.com/SinisterRectus/Discordia/blob/master/libs/utils/Permissions.lua#L182) `objects` should be `object`
- [Here](https://github.com/SinisterRectus/Discordia/blob/master/libs/iterables/Iterable.lua#L134) `satisfy` is misspelled 
- [Here](https://github.com/SinisterRectus/Discordia/blob/master/libs/client/Client.lua#L291) `stop` should be `stops`
- [Here](https://github.com/SinisterRectus/Discordia/blob/master/libs/client/Client.lua#L544) and [here](https://github.com/SinisterRectus/Discordia/blob/master/libs/client/Client.lua#L567) `users's` should be `user's`

**Comment by SinisterRectus** [comment]
Excellent work, thank you for your contribution.

**Pull request merged**
