### PR TITLE
Fast speed at voice stream start

### PR DESCRIPTION
**Pull request by Andols0**
Sometimes it might take over 800ms from the time that start is declared to the first time delay is calculated. That makes the sleep go down to 0ms for a time to catch up.
Moves the start time to the first loop.

### CODE REVIEW

**Comment by SinisterRectus** [comment]
I'm trying to figure out why this happens. Can you pull the most recent changes and do some debugging? Call `open` at the start of the code and `close` at the end of the code to measure how long it takes to execute.

For example
```lua
while true do
  open()
  -- big code block
  close()
  sleep(delay)
end
```
You can move these around within the audio stream loop to figure out what is using the most resources (probably encoding), but a measure of the whole loop would be best. Just be sure to close before sleeping, otherwise you'll measure the sleep time as execution time.

**Comment by SinisterRectus** [comment]
Here is a short audio sample if you need one: [oof.zip](https://github.com/SinisterRectus/Discordia/files/1913120/oof.zip).

**Comment by Andols0** [comment]
This the output from 
```
while elapsed < duration do
open()
local pcm = stream:read(pcm_len)
close
```

```
Andols#5974 is "Playing" oof'
2018-04-15 20:21:14 | [INFO]    | Voice : Connected to wss://eu-central351.discord.gg
2018-04-15 20:21:14 | [INFO]    | Voice : Received HELLO
2018-04-15 20:21:14 | [INFO]    | Voice : Received READY
Guessed Channel Layout for Input Stream #0.0 : stereo
dt: 971.315 | dm: 52.1025 | avg dt: 971.315 | avg dm: 52.1025
dt: 2.84494 | dm: 316.062 | avg dt: 487.08 | avg dm: 184.082
dt: 0.995934 | dm: 71.8447 | avg dt: 325.052 | avg dm: 146.67
dt: 1.70015 | dm: 68.0947 | avg dt: 244.214 | avg dm: 127.026
dt: 0.650467 | dm: 64.3447 | avg dt: 195.501 | avg dm: 114.49
dt: 0.819841 | dm: 60.5947 | avg dt: 163.054 | avg dm: 105.507
dt: 1.48239 | dm: 56.8447 | avg dt: 139.973 | avg dm: 98.5554
dt: 2.71332 | dm: 55.0752 | avg dt: 122.815 | avg dm: 93.1204
dt: 0.832497 | dm: 49.3447 | avg dt: 109.262 | avg dm: 88.2564
```

**Comment by SinisterRectus** [comment]
Is that just reading the stream? Do the other function calls have the same time? You can break the loop into 6 discrete steps. I'm curious to see if all or just some are slow on the first loop.

Read stream:
```lua
local pcm = stream:read(pcm_len)
if not pcm then break end
```
Encode audio:
```lua
local data, len = encoder:encode(pcm, pcm_len, frame_size, pcm_len * 2)
if not data then break end
```
Prepare header:
```lua
local s, t = self._s, self._t
local header = pack(HEADER_FMT, 0x80, 0x78, s, t, ssrc)

s = s + 1
t = t + frame_size

self._s = s > MAX_SEQUENCE and 0 or s
self._t = t > MAX_TIMESTAMP and 0 or t
```
Encrypt packet:
```lua
local encrypted, encrypted_len = sodium.encrypt(data, len, header .. PADDING, key)
if not encrypted then break end
```
Send packet:
```lua
local packet = header .. ffi_string(encrypted, encrypted_len)
udp:send(packet, ip, port)
```
Calculate delay:
```lua
elapsed = elapsed + FRAME_DURATION
local delay = elapsed - (hrtime() - start) * MS_PER_NS
```

**Comment by Andols0** [comment]
I wrapped all of the parts above in a ``open() close()`` and i modified close() to take a string input and also print that.

Raspberry Pi
```
'Andols#5974 is "Playing" oof'
2018-04-15 20:44:24 | [INFO]    | Voice : Connected to wss://eu-central351.discord.gg
2018-04-15 20:44:24 | [INFO]    | Voice : Received HELLO
2018-04-15 20:44:24 | [INFO]    | Voice : Received READY
Run: 1
Guessed Channel Layout for Input Stream #0.0 : stereo
dt: 950.96 | dm: 100.521 | avg dt: 4.86093 | avg dm: 6.57425	Read stream
dt: 2.80947 | dm: 7.53125 | avg dt: 4.85627 | avg dm: 6.57643	Encode audio
dt: 0.206719 | dm: 0.0898438 | avg dt: 4.84572 | avg dm: 6.56172	Prepare header
dt: 0.062864 | dm: 0.34375 | avg dt: 4.8349 | avg dm: 6.54765	Encrypt packet
dt: 0.290729 | dm: 0.863281 | avg dt: 4.82465 | avg dm: 6.53482	Send Packet
dt: 0.010052 | dm: 0 | avg dt: 4.8138 | avg dm: 6.5201	Calculate delay
Run: 2
dt: 0.636456 | dm: 39.5947 | avg dt: 4.80441 | avg dm: 6.59443	Read stream
dt: 2.46994 | dm: 7.53125 | avg dt: 4.79918 | avg dm: 6.59653	Encode audio
dt: 0.039375 | dm: 0.0693359 | avg dt: 4.78853 | avg dm: 6.58193	Prepare header
dt: 0.043906 | dm: 0.212891 | avg dt: 4.77794 | avg dm: 6.56771	Encrypt packet
dt: 0.038177 | dm: 0.601563 | avg dt: 4.76739 | avg dm: 6.55442	Send Packet
dt: 0.002656 | dm: 0 | avg dt: 4.7568 | avg dm: 6.53986	Calculate delay
Run: 3
dt: 0.623696 | dm: 35.8447 | avg dt: 4.74763 | avg dm: 6.60483	Read stream
dt: 2.46359 | dm: 7.53125 | avg dt: 4.74258 | avg dm: 6.60688	Encode audio
dt: 0.045833 | dm: 0.0878906 | avg dt: 4.73221 | avg dm: 6.59249	Prepare header
dt: 0.04625 | dm: 0.213867 | avg dt: 4.72189 | avg dm: 6.57844	Encrypt packet
dt: 0.050833 | dm: 0.603516 | avg dt: 4.71162 | avg dm: 6.56531	Send Packet
dt: 0.005208 | dm: 0 | avg dt: 4.7013 | avg dm: 6.55091	Calculate delay
Run: 4
dt: 0.629425 | dm: 32.0947 | avg dt: 4.69239 | avg dm: 6.60681	Read stream
dt: 9.71487 | dm: 7.53125 | avg dt: 4.70336 | avg dm: 6.60883	Encode audio
dt: 0.048386 | dm: 0.0878906 | avg dt: 4.69322 | avg dm: 6.59462	Prepare header
dt: 0.049323 | dm: 0.213867 | avg dt: 4.68312 | avg dm: 6.58075	Encrypt packet
dt: 0.051197 | dm: 0.603516 | avg dt: 4.67307 | avg dm: 6.56778	Send Packet
dt: 0.039792 | dm: 0 | avg dt: 4.66305 | avg dm: 6.55357	Calculate delay
```
And pc
```
'Andols#5974 is "Playing" oof'
2018-04-15 20:46:44 | [INFO]    | Voice : Connected to wss://eu-central351.discord.gg
2018-04-15 20:46:44 | [INFO]    | Voice : Received HELLO
2018-04-15 20:46:44 | [INFO]    | Voice : Received READY
Run: 1
Guessed Channel Layout for Input Stream #0.0 : stereo
dt: 33.8949 | dm: 51.04 | avg dt: 33.8949 | avg dm: 51.04       Read stream
dt: 0.363518 | dm: 11.6406 | avg dt: 17.1292 | avg dm: 31.3403  Encode audio
dt: 0.008132 | dm: 0.0898438 | avg dt: 11.4222 | avg dm: 20.9235        Prepare header
dt: 0.024395 | dm: 0.374023 | avg dt: 8.57273 | avg dm: 15.7861 Encrypt packet
dt: 0.05391 | dm: 0.767578 | avg dt: 6.86897 | avg dm: 12.7824  Send Packet
dt: 0.000301 | dm: 0 | avg dt: 5.72419 | avg dm: 10.652 Calculate delay
Run: 2
dt: 0.234615 | dm: 336.069 | avg dt: 4.93996 | avg dm: 57.1402  Read stream
dt: 0.183416 | dm: 7.53125 | avg dt: 4.3454 | avg dm: 50.9391   Encode audio
dt: 0.007228 | dm: 0.0693359 | avg dt: 3.86338 | avg dm: 45.2869        Prepare header
dt: 0.010842 | dm: 0.228516 | avg dt: 3.47812 | avg dm: 40.7811 Encrypt packet
dt: 0.048489 | dm: 0.507813 | avg dt: 3.16634 | avg dm: 37.1199 Send Packet
dt: 0.000602 | dm: 0 | avg dt: 2.90253 | avg dm: 34.0265        Calculate delay
Run: 3
dt: 0.090352 | dm: 75.8447 | avg dt: 2.68621 | avg dm: 37.2433  Read stream
dt: 0.197872 | dm: 7.53125 | avg dt: 2.50847 | avg dm: 35.121   Encode audio
dt: 0.008734 | dm: 0.0878906 | avg dt: 2.34182 | avg dm: 32.7855        Prepare header
dt: 0.01777 | dm: 0.229492 | avg dt: 2.19657 | avg dm: 30.7507  Encrypt packet
dt: 0.126192 | dm: 0.509766 | avg dt: 2.07478 | avg dm: 28.9719 Send Packet
dt: 0.000602 | dm: 0 | avg dt: 1.95955 | avg dm: 27.3623        Calculate delay
Run: 4
dt: 0.081318 | dm: 72.0947 | avg dt: 1.86069 | avg dm: 29.7166  Read stream
dt: 0.277081 | dm: 7.53125 | avg dt: 1.78151 | avg dm: 28.6074  Encode audio
dt: 0.009638 | dm: 0.0878906 | avg dt: 1.69714 | avg dm: 27.2493        Prepare header
dt: 0.01295 | dm: 0.229492 | avg dt: 1.62058 | avg dm: 26.0211  Encrypt packet
dt: 0.116856 | dm: 0.509766 | avg dt: 1.5552 | avg dm: 24.9119  Send Packet
dt: 0.000301 | dm: 0 | avg dt: 1.49042 | avg dm: 23.8739        Calculate delay
```

**Comment by SinisterRectus** [comment]
Looks like it's waiting for FFmpeg to spin up. Hmmm.

**Comment by SinisterRectus** [comment]
Using the library code (not your PR code), if you put a short sleep before the loop, do you still have the timing issue?

```lua
sleep(1000)
local start = hrtime()
while elapsed < duration do
  -- audio loop
end
```

**Comment by Mehgugs** [comment]
Given that it seems likely it's the provider's initial read taking time (the first stream:read) perhaps something like this [commit](https://github.com/Mehgugs/Discordia/commit/556ad7730f4d977e12f7a0100061677d83ec98ac) would be more appropriate, some initial tests (no accurate debugging yet) show no timing issues on playback start.

I have actually noticed (sadly unable to reproduce either error reliably) the speed change occurring mid stream too, which makes me think it is probably an external issue with whatever is providing the PCM stream rather than a discordia issue.

**Comment by SinisterRectus** [comment]
That's a useless goto. Just use the if statement to skip the loop.

I need to wait for results from people who can reproduce the issue.

**Comment by Andols0** [comment]
Yes placing a sleep there also "fixes" it
```'Andols#5974 is "Playing" oof'
2018-04-16 17:17:17 | [INFO]    | Voice : Connected to wss://eu-central177.discord.gg
2018-04-16 17:17:17 | [INFO]    | Voice : Received HELLO
2018-04-16 17:17:17 | [INFO]    | Voice : Received READY
Guessed Channel Layout for Input Stream #0.0 : stereo
Run: 1
dt: 1.98369 | dm: 219.032 | avg dt: 1.98369 | avg dm: 219.032	Read stream
Run: 2
dt: 2.13848 | dm: 71.5947 | avg dt: 2.06109 | avg dm: 145.313	Read stream
Run: 3
dt: 0.82432 | dm: 67.8447 | avg dt: 1.64883 | avg dm: 119.491	Read stream
Run: 4
dt: 0.718539 | dm: 64.0947 | avg dt: 1.41626 | avg dm: 105.642	Read stream
```

**Comment by SinisterRectus** [comment]
I was hoping it wouldn't, since it's not really a fix. I have three more ideas:

1. Replace the sleep with a zero-length read. This would fill the internal buffer with some data so that the first actual read does not rely on the external process. This would prevent the delay at the start, but it would do nothing if the delay occurs mid-stream.
```lua
stream:read(0)
local start = hrtime()
while elapsed < duration do
  -- audio loop
end
```

2. Adjust the sleep delay minimum to something higher than 0, based on the FRAME_DURATION. This will prevent the speed up, but has the potential over compensate and slow down the packet sending.
```lua
elapsed = elapsed + FRAME_DURATION
local delay = elapsed - (hrtime() - start) * MS_PER_NS
sleep(max(delay, 0.5 * FRAME_DURATION))
```

3. Use a queue as a packet buffer to smooth out the inconsistencies in the time it takes to read and process the stream. If my thinking is correct, this will work as long as the average time to add a packet to the buffer is less than the FRAME_DURATION and as long as the time to send a packet is also less than the FRAME_DURATION.

4. Admit that my latency handling algorithm is not properly formed and write a totally new one.

**Comment by Mehgugs** [comment]
I'm currently testing read(0) and it doesn't seem to improve the length of the initial read, 
[You can see how im getting these numbers here](https://github.com/Mehgugs/Discordia/commit/7f3aea338a18f225b13f8d792274b568c47b966e)

```
SoX: added effect 'gain'
Initial stream read.
dt: 276.906 | dm: 92.8066 | avg dt: 276.906 | avg dm: 92.8066
SoX: added effect 'gain'
Initial stream read.
dt: 580.197 | dm: 71.5186 | avg dt: 428.552 | avg dm: 82.1626
SoX: added effect 'gain'
Initial stream read.
dt: 109.335 | dm: 71.8271 | avg dt: 322.146 | avg dm: 78.7174
SoX: added effect 'gain'
Initial stream read.
dt: 612.94 | dm: 71.2568 | avg dt: 394.845 | avg dm: 76.8523
SoX: added effect 'gain'
Initial stream read.
dt: 137.608 | dm: 71.2256 | avg dt: 343.397 | avg dm: 75.727
```

**Comment by SinisterRectus** [comment]
Since the issue has grown larger than what this PR addresses, I'm going to close this. Redirect discussion to issue #116.

**Comment by SinisterRectus** [comment]
The reason why I won't accept this PR straight away is because it's only avoiding the issue. It basically just skips the first packet and assumes that the wait time should be exactly 20 ms. This isn't necessarily a bad work-around, it's just not ideal if we can fix the underlying issue.

**Pull request closed without merging**
