### PR TITLE
License update for 2018

### PR DESCRIPTION
**Pull request by Sanjay-B**

### CODE REVIEW

**Comment by SinisterRectus** [comment]
Update package.lua, too.

**Comment by Sanjay-B** [comment]
My mistake.
https://github.com/SinisterRectus/Discordia/pull/112

**Comment by SinisterRectus** [comment]
What are you doing. Just commit the change to the same branch. https://help.github.com/articles/about-pull-requests/

**Comment by Sanjay-B** [comment]
Sorry about that mess. I was attempting to do it on my mobile device. Should be corrected and/or fixed.

**Pull request merged**
